import { MoodItem } from './types';

export const MOODS: MoodItem[] = [
  {
    id: 'happy',
    name: 'Happy',
    emoji: '😊',
    quote: 'Keep smiling! Your happiness can brighten someone’s day.',
    message: 'Enjoy your happy moment! 🌈',
    colorScheme: {
      name: 'Happy Yellow',
      buttonBg: 'bg-[#FFF9C4]',
      buttonBorder: 'border-[#FFD54F]',
      buttonHover: 'hover:bg-[#FFF59D] hover:border-[#FFCA28]',
      buttonShadow: 'shadow-yellow-200/50',
      badgeColor: 'bg-[#FFD54F]/30 text-[#F57F17] border-[#FFD54F]',
      detailBg: 'bg-white',
      detailBorder: 'border-[#FFD54F]',
      textColor: 'text-[#37474F]',
      accentColor: 'text-[#F57F17]',
      bubbleGradient: 'from-[#FFF9C4] to-[#FFD54F]',
      sparkleEmoji: '✨',
    },
    kidTip: 'Do a happy little wiggle dance or share a giant smile with someone! 💛',
  },
  {
    id: 'sad',
    name: 'Sad',
    emoji: '😢',
    quote: 'It’s okay to feel sad. Tomorrow can bring a new smile.',
    message: 'Take a deep breath. You are not alone. 💙',
    colorScheme: {
      name: 'Gentle Sky Blue',
      buttonBg: 'bg-[#E3F2FD]',
      buttonBorder: 'border-[#64B5F6]',
      buttonHover: 'hover:bg-[#BBDEFB] hover:border-[#42A5F5]',
      buttonShadow: 'shadow-blue-200/50',
      badgeColor: 'bg-[#64B5F6]/20 text-[#1976D2] border-[#64B5F6]',
      detailBg: 'bg-white',
      detailBorder: 'border-[#64B5F6]',
      textColor: 'text-[#37474F]',
      accentColor: 'text-[#1976D2]',
      bubbleGradient: 'from-[#E3F2FD] to-[#64B5F6]',
      sparkleEmoji: '💧',
    },
    kidTip: 'Hug your favorite pillow, pet, or ask someone for a gentle warm hug. 🧸',
  },
  {
    id: 'angry',
    name: 'Angry',
    emoji: '😡',
    quote: 'Take a breath, count to five, and give yourself time.',
    message: 'It’s okay to be angry. You can choose what to do next. 🌱',
    colorScheme: {
      name: 'Coral Red',
      buttonBg: 'bg-[#FFEBEE]',
      buttonBorder: 'border-[#EF5350]',
      buttonHover: 'hover:bg-[#FFCDD2] hover:border-[#E53935]',
      buttonShadow: 'shadow-red-200/50',
      badgeColor: 'bg-[#EF5350]/20 text-[#D32F2F] border-[#EF5350]',
      detailBg: 'bg-white',
      detailBorder: 'border-[#EF5350]',
      textColor: 'text-[#37474F]',
      accentColor: 'text-[#D32F2F]',
      bubbleGradient: 'from-[#FFEBEE] to-[#EF5350]',
      sparkleEmoji: '🔥',
    },
    kidTip: 'Count: 1... 2... 3... 4... 5... and blow out imaginary birthday candles! 🎂',
  },
  {
    id: 'scared',
    name: 'Scared',
    emoji: '😨',
    quote: 'Being brave doesn’t mean you are never scared.',
    message: 'Take a deep breath. You are stronger than you think! ⭐',
    colorScheme: {
      name: 'Cozy Lavender',
      buttonBg: 'bg-[#F3E5F5]',
      buttonBorder: 'border-[#9575CD]',
      buttonHover: 'hover:bg-[#E1BEE7] hover:border-[#7E57C2]',
      buttonShadow: 'shadow-purple-200/50',
      badgeColor: 'bg-[#9575CD]/20 text-[#5E35B1] border-[#9575CD]',
      detailBg: 'bg-white',
      detailBorder: 'border-[#9575CD]',
      textColor: 'text-[#37474F]',
      accentColor: 'text-[#5E35B1]',
      bubbleGradient: 'from-[#F3E5F5] to-[#9575CD]',
      sparkleEmoji: '🌟',
    },
    kidTip: 'Put your hands on your heart and say: “I am safe, I am strong, I am okay.” 💜',
  },
  {
    id: 'tired',
    name: 'Tired',
    emoji: '😴',
    quote: 'Rest is important. Even superheroes need a break!',
    message: 'Take some time to relax and recharge. 💤',
    colorScheme: {
      name: 'Sleepy Twilight',
      buttonBg: 'bg-[#ECEFF1]',
      buttonBorder: 'border-[#90A4AE]',
      buttonHover: 'hover:bg-[#CFD8DC] hover:border-[#78909C]',
      buttonShadow: 'shadow-slate-200/50',
      badgeColor: 'bg-[#90A4AE]/20 text-[#455A64] border-[#90A4AE]',
      detailBg: 'bg-white',
      detailBorder: 'border-[#90A4AE]',
      textColor: 'text-[#37474F]',
      accentColor: 'text-[#455A64]',
      bubbleGradient: 'from-[#ECEFF1] to-[#90A4AE]',
      sparkleEmoji: '🌙',
    },
    kidTip: 'Give a big sleepy yawn, stretch your arms out wide, and rest your eyes. 🛌',
  },
  {
    id: 'excited',
    name: 'Excited',
    emoji: '🤩',
    quote: 'Let your excitement shine!',
    message: 'Have fun and enjoy the moment! 🎉',
    colorScheme: {
      name: 'Vibrant Peach',
      buttonBg: 'bg-[#FBE9E7]',
      buttonBorder: 'border-[#FF8A65]',
      buttonHover: 'hover:bg-[#FFCCBC] hover:border-[#FF7043]',
      buttonShadow: 'shadow-orange-200/50',
      badgeColor: 'bg-[#FF8A65]/20 text-[#E64A19] border-[#FF8A65]',
      detailBg: 'bg-white',
      detailBorder: 'border-[#FF8A65]',
      textColor: 'text-[#37474F]',
      accentColor: 'text-[#E64A19]',
      bubbleGradient: 'from-[#FBE9E7] to-[#FF8A65]',
      sparkleEmoji: '✨',
    },
    kidTip: 'High-five in the air and celebrate what is making you happy! 🥳',
  },
  {
    id: 'calm',
    name: 'Calm',
    emoji: '😌',
    quote: 'A calm mind can find beautiful ideas.',
    message: 'Keep breathing slowly and enjoy the peace. 🍃',
    colorScheme: {
      name: 'Peaceful Meadow',
      buttonBg: 'bg-[#E8F5E9]',
      buttonBorder: 'border-[#81C784]',
      buttonHover: 'hover:bg-[#C8E6C9] hover:border-[#66BB6A]',
      buttonShadow: 'shadow-green-200/50',
      badgeColor: 'bg-[#81C784]/20 text-[#2E7D32] border-[#81C784]',
      detailBg: 'bg-white',
      detailBorder: 'border-[#81C784]',
      textColor: 'text-[#37474F]',
      accentColor: 'text-[#2E7D32]',
      bubbleGradient: 'from-[#E8F5E9] to-[#81C784]',
      sparkleEmoji: '🌿',
    },
    kidTip: 'Listen closely to 3 quiet sounds around you right now. 🍃',
  },
  {
    id: 'loved',
    name: 'Loved',
    emoji: '😍',
    quote: 'You are special, and you are loved.',
    message: 'Share some kindness today! 💕',
    colorScheme: {
      name: 'Sweet Blossom',
      buttonBg: 'bg-[#FCE4EC]',
      buttonBorder: 'border-[#F06292]',
      buttonHover: 'hover:bg-[#F8BBD0] hover:border-[#EC407A]',
      buttonShadow: 'shadow-pink-200/50',
      badgeColor: 'bg-[#F06292]/20 text-[#C2185B] border-[#F06292]',
      detailBg: 'bg-white',
      detailBorder: 'border-[#F06292]',
      textColor: 'text-[#37474F]',
      accentColor: 'text-[#C2185B]',
      bubbleGradient: 'from-[#FCE4EC] to-[#F06292]',
      sparkleEmoji: '💖',
    },
    kidTip: 'Draw a mini heart on a paper or say “thank you” to someone you love! 💌',
  },
  {
    id: 'confused',
    name: 'Confused',
    emoji: '😕',
    quote: 'It’s okay not to know everything. Keep learning!',
    message: 'Ask a question and take it one step at a time. 💡',
    colorScheme: {
      name: 'Teal Curiosity',
      buttonBg: 'bg-[#E0F2F1]',
      buttonBorder: 'border-[#4DB6AC]',
      buttonHover: 'hover:bg-[#B2DFDB] hover:border-[#26A69A]',
      buttonShadow: 'shadow-teal-200/50',
      badgeColor: 'bg-[#4DB6AC]/20 text-[#00796B] border-[#4DB6AC]',
      detailBg: 'bg-white',
      detailBorder: 'border-[#4DB6AC]',
      textColor: 'text-[#37474F]',
      accentColor: 'text-[#00796B]',
      bubbleGradient: 'from-[#E0F2F1] to-[#4DB6AC]',
      sparkleEmoji: '💡',
    },
    kidTip: 'Remember: Curious brains grow the biggest! Ask your question with a smile. 🔍',
  },
  {
    id: 'confident',
    name: 'Confident',
    emoji: '😎',
    quote: 'Believe in yourself. You can do amazing things!',
    message: 'Keep going and show what you can do! 🚀',
    colorScheme: {
      name: 'Sky Cyan',
      buttonBg: 'bg-[#E1F5FE]',
      buttonBorder: 'border-[#4FC3F7]',
      buttonHover: 'hover:bg-[#B3E5FC] hover:border-[#29B6F6]',
      buttonShadow: 'shadow-cyan-200/50',
      badgeColor: 'bg-[#4FC3F7]/20 text-[#0288D1] border-[#4FC3F7]',
      detailBg: 'bg-white',
      detailBorder: 'border-[#4FC3F7]',
      textColor: 'text-[#37474F]',
      accentColor: 'text-[#0288D1]',
      bubbleGradient: 'from-[#E1F5FE] to-[#4FC3F7]',
      sparkleEmoji: '⭐',
    },
    kidTip: 'Stand tall with superhero hands on your hips and take a power breath! 🦸',
  },
];
